substitutions:
  # Screen Size
  screen_height: '480px'
  screen_width: '480px'

  screen_height_px: '480'
  screen_width_px: '480'

  #theme
  text_font: roboto24
  text_color: white

  info_font: poetsen48


packages:
  # Harware description file
  hardware: !include modules/hardware/sdl.yaml
  fonts: !include modules/base/fonts.yaml
  images: !include modules/base/images.yaml

  wind: !include modules/applications/wind.yaml
  energy: !include modules/applications/energry.yaml
  settingss: !include modules/applications/settings.yaml