---
# Settings Screen

  - obj:
      height: $screen_height
      width: $screen_width
      align: CENTER
      bg_color: 0x000000
      border_width: 0
      pad_all: 0
      widgets:
        # - image:
        #     src: boot_logo_90px
        #     pad_bottom: 10
        - label:
            id: settings_label
            text: "Under construction"
            align: CENTER
            text_color: 0xFFFFFF
            text_font: roboto32
