substitutions:
  repin: GPIO1
  dcpin: GPIO2
  bkpin: GPIO3
  clpin: GPIO6
  mopin: GPIO7
  cspin: GPIO10

esphome:
  name: energymonitor
  friendly_name: Energy Monitor

esp32:
  board: esp32-c3-devkitm-1
  # board: esp32dev
  framework:
    type: arduino

# ota:
#   - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source: github://batuakan/ESPHomeSignalK@main
    components: [ signalk ]
  - source: github://bearpawmaxim/esphome@pr3625fix
    components: [ gc9a01 ]
  - source: github://GadgetFactory/CST816S_touchscreen@1.0.0 

# captive_portal:

logger:
  level: DEBUG

font:
  - file: 'fonts/PoetsenOne-Regular.ttf'
    id: font_32
    size: 32

signalk:
  host: 192.168.0.3
  # port: 3000 # defaults to 3000

sensor:

  - platform: signalk
    id: electrical_batteries_shunt_current
    path: electrical.batteries.shunt.current
    period: 200
    accuracy_decimals: 2
    on_value:
      - lvgl.label.update:
          id: shunt_current_label
          text:
            format: "%.1f m/s"
            args: [ 'x' ]

  - platform: signalk
    id: electrical_solar_mppt_current
    path: electrical.solar.mppt.current
    period: 200
    accuracy_decimals: 2
    on_value:
      - lvgl.label.update:
          id: solar_current_label
          text:
            format: "%.1f m/s"
            args: [ 'x' ]

  - platform: signalk
    id: electrical_batteries_shunt_voltage
    path: electrical.batteries.shunt.voltage
    period: 200
    accuracy_decimals: 2
    on_value:
      - lvgl.indicator.update:
          id: battery_voltage_needle
          value: !lambda return x * 10;

  - platform: signalk
    id: electrical_batteries_shunt_capacity_stateOfCharge
    path: electrical.batteries.shunt.capacity.stateOfCharge
    period: 200
    accuracy_decimals: 2
    on_value:
      - lvgl.indicator.update:
          id: battery_state_of_charge_needle
          value: !lambda return x * 100;

  # - platform: homeassistant
  #   id: shorepower_current
  #   entity_id: tze284_cjbofhxw_ts0601_current
  #   accuracy_decimals: 2
  #   on_value:
  #     - lvgl.label.update:
  #         id: shorepower_current_label
  #         text:
  #           format: "%.1f m/s"
  #           args: [ 'x' ]

# needs to have at least one instance of signalk text_sensor for the compiler to build.
# TODO: remove the necesity to include a text_sensor
text_sensor:
  - platform: signalk
    id: name
    path: name


spi:
  mosi_pin: $mopin
  clk_pin: $clpin
#mosi = Master Out Slave In
#miso = Master In Slave Out or fermented bean paste. In this case, most likely the former rather than the latter. Doesn't matter as not used.

# Need to turn on backlight as by default is not on
output:
  - platform: ledc
    pin: $bkpin
    id: gpio_3_backlight_pwm

light:
  - platform: monochromatic
    output: gpio_3_backlight_pwm
    name: "Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON

display:
  - platform: gc9a01
    id: watchface
    reset_pin: $repin
    cs_pin: $cspin
    dc_pin: $dcpin

lvgl:
    pages:
      - id: meter_page
        bg_color: 0x000000
        widgets:
          - obj:
              height: 260
              width: 260
              align: CENTER
              bg_color: 0x000000
              border_width: 0
              pad_all: 14
              widgets:
                - meter:
                    align: CENTER
                    height: 260
                    width: 260
                    bg_color: 0x000000
                    scales:
                      - range_from: 150 # scale for the needle value
                        range_to: 100
                        angle_range: 80
                        rotation: 10
                        ticks:
                          width: 1
                          count: 6
                          length: 10
                        indicators:
                          - line:
                              id: battery_voltage_needle
                              width: 4
                              color: 0xFF0000
                              r_mod: -4
                              value: 132
                          - line:
                              id: engine_battery_voltage_needle
                              width: 4
                              color: 0x00FF00
                              r_mod: -4
                              value: 128
                          - tick_style:
                              start_value: 150
                              end_value: 100
                              color_start: 0xFF00FF
                              color_end: 0xFF00FF
                              width: 2
                              
                      
                      - range_from: 0 # scale for the value labels
                        range_to: 100
                        angle_range: 270
                        rotation: 90
                        ticks:
                          width: 3
                          count: 51
                          length: 20
                        indicators:
                          - line:
                              id: battery_state_of_charge_needle
                              width: 14
                              color: 0xFFFFFF
                              r_mod: -4
                              value: 55
                          - tick_style:
                              start_value: 0
                              end_value: 20
                              color_start: 0xFF0000
                              color_end: 0xFF0000
                              width: 1
                              local: true
                          - tick_style:
                              start_value: 21
                              end_value: 50
                              color_start: 0xFFFF00
                              color_end: 0xFFFF00
                              width: 2
                              local: true
                          - tick_style:
                              start_value: 51
                              end_value: 100
                              color_start: 0x00FF00
                              color_end: 0x00FF00
                              width: 3
                              local: true
                - obj: # to cover the middle part of meter indicator line
                    height: 160
                    width: 160
                    radius: 80
                    align: CENTER
                    border_width: 0
                    bg_color: 0x000000

                - label:
                    id: shorepower_current_label
                    text: "000.0Ah"
                    align: CENTER
                    text_color: 0xFFFFFF
                    text_font: font_32
                    y: -40
                - label: 
                    id: shunt_current_label
                    text: "000.0Ah"
                    align: CENTER
                    text_color: 0xFFFFFF
                    text_font: font_32
                    y: 0
                - label:
                    id: solar_current_label
                    text: "000.0Ah"
                    align: CENTER
                    text_color: 0xFFFF00
                    text_font: font_32
                    y: 40
